### ISSUE TITLE
Quickfix not displaying

### ISSUE THREAD

**Issue by davejacobs** [duskhacker/sweet-rspec-vim#8]
I can't get the Quickfix buffer to show up. I have the following plugins installed, all using Pathogen (some names are shortened, but they're all the canonical ones as far as I can tell):

ack
clojure
coffeescript
command-t
conque
cucumber
endwise
fugitive
haml
html5
javascript
markdown
nerdcommenter
nerdtree
pastie
rails
rake
ruby
solarized
supertab
surround
sweet-rspec

**Comment by duskhacker** [comment]
You may want to use this fork:

https://github.com/ericdwhite/sweet-rspec-vim

Until I can pull it in. Mr. White also uses pathogen.

**Comment by duskhacker** [comment]
Do an update and let me know if you are still having problems.

**Comment by davejacobs** [comment]
Looks good now, thanks!
